GET http://localhost:8080/orders/all

###
POST http://localhost:8080/orders/new HTTP/1.1
content-type: application/json

{
    "name": "denis",
    "total": 100000.00
}

###
POST http://localhost:8080/query

###