// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewOrder struct {
	Name  string  `json:"name"`
	Total float64 `json:"total"`
}

type Query struct {
}
